package org.fix4j.spec.fix50sp2.msgtype;

import org.fix4j.test.fixspec.BaseGroupType;
import org.fix4j.test.fixspec.BaseMsgType;
import org.fix4j.spec.fix50sp2.FieldTypes;

public class TradingSessionStatus extends BaseMsgType{
    public static final TradingSessionStatus INSTANCE = new TradingSessionStatus();

    private TradingSessionStatus() {
        super(
            "TradingSessionStatus",
            "h",
            "app",
            FieldTypes.ApplID.required(false),
            FieldTypes.ApplSeqNum.required(false),
            FieldTypes.ApplLastSeqNum.required(false),
            FieldTypes.ApplResendFlag.required(false),
            FieldTypes.TradSesReqID.required(false),
            FieldTypes.MarketID.required(false),
            FieldTypes.MarketSegmentID.required(false),
            FieldTypes.TradingSessionID.required(true),
            FieldTypes.TradingSessionSubID.required(false),
            FieldTypes.TradSesMethod.required(false),
            FieldTypes.TradSesMode.required(false),
            FieldTypes.UnsolicitedIndicator.required(false),
            FieldTypes.TradSesStatus.required(true),
            FieldTypes.TradSesEvent.required(false),
            FieldTypes.TradSesStatusRejReason.required(false),
            FieldTypes.TradSesStartTime.required(false),
            FieldTypes.TradSesOpenTime.required(false),
            FieldTypes.TradSesPreCloseTime.required(false),
            FieldTypes.TradSesCloseTime.required(false),
            FieldTypes.TradSesEndTime.required(false),
            FieldTypes.TotalVolumeTraded.required(false),
            FieldTypes.Text.required(false),
            FieldTypes.EncodedTextLen.required(false),
            FieldTypes.EncodedText.required(false),
            FieldTypes.Symbol.required(false),
            FieldTypes.SymbolSfx.required(false),
            FieldTypes.SecurityID.required(false),
            FieldTypes.SecurityIDSource.required(false),
            new BaseGroupType(
                FieldTypes.NoSecurityAltID.required(false),
                FieldTypes.SecurityAltID.required(false),
                FieldTypes.SecurityAltIDSource.required(false)
            ),
            FieldTypes.Product.required(false),
            FieldTypes.SecurityGroup.required(false),
            FieldTypes.ProductComplex.required(false),
            FieldTypes.CFICode.required(false),
            FieldTypes.SecurityType.required(false),
            FieldTypes.SecuritySubType.required(false),
            FieldTypes.MaturityMonthYear.required(false),
            FieldTypes.MaturityDate.required(false),
            FieldTypes.SecurityStatus.required(false),
            FieldTypes.SettleOnOpenFlag.required(false),
            FieldTypes.InstrmtAssignmentMethod.required(false),
            FieldTypes.MaturityTime.required(false),
            FieldTypes.CouponPaymentDate.required(false),
            FieldTypes.RestructuringType.required(false),
            FieldTypes.Seniority.required(false),
            FieldTypes.NotionalPercentageOutstanding.required(false),
            FieldTypes.OriginalNotionalPercentageOutstanding.required(false),
            FieldTypes.AttachmentPoint.required(false),
            FieldTypes.DetachmentPoint.required(false),
            FieldTypes.IssueDate.required(false),
            FieldTypes.RepoCollateralSecurityType.required(false),
            FieldTypes.RepurchaseTerm.required(false),
            FieldTypes.RepurchaseRate.required(false),
            FieldTypes.Factor.required(false),
            FieldTypes.CreditRating.required(false),
            FieldTypes.InstrRegistry.required(false),
            FieldTypes.CountryOfIssue.required(false),
            FieldTypes.StateOrProvinceOfIssue.required(false),
            FieldTypes.LocaleOfIssue.required(false),
            FieldTypes.RedemptionDate.required(false),
            FieldTypes.StrikePrice.required(false),
            FieldTypes.StrikeCurrency.required(false),
            FieldTypes.StrikeMultiplier.required(false),
            FieldTypes.StrikeValue.required(false),
            FieldTypes.StrikePriceDeterminationMethod.required(false),
            FieldTypes.StrikePriceBoundaryMethod.required(false),
            FieldTypes.StrikePriceBoundaryPrecision.required(false),
            FieldTypes.UnderlyingPriceDeterminationMethod.required(false),
            FieldTypes.OptAttribute.required(false),
            FieldTypes.ContractMultiplier.required(false),
            FieldTypes.MinPriceIncrement.required(false),
            FieldTypes.UnitOfMeasure.required(false),
            FieldTypes.TimeUnit.required(false),
            FieldTypes.MinPriceIncrementAmount.required(false),
            FieldTypes.UnitOfMeasureQty.required(false),
            FieldTypes.PriceUnitOfMeasure.required(false),
            FieldTypes.PriceUnitOfMeasureQty.required(false),
            FieldTypes.SettlMethod.required(false),
            FieldTypes.ExerciseStyle.required(false),
            FieldTypes.OptPayoutAmount.required(false),
            FieldTypes.PriceQuoteMethod.required(false),
            FieldTypes.ListMethod.required(false),
            FieldTypes.CapPrice.required(false),
            FieldTypes.FloorPrice.required(false),
            FieldTypes.PutOrCall.required(false),
            FieldTypes.FlexibleIndicator.required(false),
            FieldTypes.FlexProductEligibilityIndicator.required(false),
            FieldTypes.ValuationMethod.required(false),
            FieldTypes.ContractMultiplierUnit.required(false),
            FieldTypes.FlowScheduleType.required(false),
            FieldTypes.OptPayoutType.required(false),
            FieldTypes.CouponRate.required(false),
            FieldTypes.SecurityExchange.required(false),
            FieldTypes.PositionLimit.required(false),
            FieldTypes.NTPositionLimit.required(false),
            FieldTypes.Issuer.required(false),
            FieldTypes.EncodedIssuerLen.required(false),
            FieldTypes.EncodedIssuer.required(false),
            FieldTypes.SecurityDesc.required(false),
            FieldTypes.EncodedSecurityDescLen.required(false),
            FieldTypes.EncodedSecurityDesc.required(false),
            FieldTypes.SecurityXMLLen.required(false),
            FieldTypes.SecurityXML.required(false),
            FieldTypes.SecurityXMLSchema.required(false),
            FieldTypes.Pool.required(false),
            FieldTypes.ContractSettlMonth.required(false),
            FieldTypes.CPProgram.required(false),
            FieldTypes.CPRegType.required(false),
            new BaseGroupType(
                FieldTypes.NoEvents.required(false),
                FieldTypes.EventType.required(false),
                FieldTypes.EventDate.required(false),
                FieldTypes.EventTime.required(false),
                FieldTypes.EventPx.required(false),
                FieldTypes.EventText.required(false)
            ),
            FieldTypes.DatedDate.required(false),
            FieldTypes.InterestAccrualDate.required(false),
            new BaseGroupType(
                FieldTypes.NoInstrumentParties.required(false),
                FieldTypes.InstrumentPartyID.required(false),
                FieldTypes.InstrumentPartyIDSource.required(false),
                FieldTypes.InstrumentPartyRole.required(false),
                new BaseGroupType(
                    FieldTypes.NoInstrumentPartySubIDs.required(false),
                    FieldTypes.InstrumentPartySubID.required(false),
                    FieldTypes.InstrumentPartySubIDType.required(false)
                )
            ),
            new BaseGroupType(
                FieldTypes.NoComplexEvents.required(false),
                FieldTypes.ComplexEventType.required(false),
                FieldTypes.ComplexOptPayoutAmount.required(false),
                FieldTypes.ComplexEventPrice.required(false),
                FieldTypes.ComplexEventPriceBoundaryMethod.required(false),
                FieldTypes.ComplexEventPriceBoundaryPrecision.required(false),
                FieldTypes.ComplexEventPriceTimeType.required(false),
                FieldTypes.ComplexEventCondition.required(false),
                new BaseGroupType(
                    FieldTypes.NoComplexEventDates.required(false),
                    FieldTypes.ComplexEventStartDate.required(false),
                    FieldTypes.ComplexEventEndDate.required(false),
                    new BaseGroupType(
                        FieldTypes.NoComplexEventTimes.required(false),
                        FieldTypes.ComplexEventStartTime.required(false),
                        FieldTypes.ComplexEventEndTime.required(false)
                    )
                )
            )
        );
    }
}
